### ISSUE TITLE
Line implement PerpendicularFrames

### ISSUE THREAD

**Issue by cesarecaoduro** [GSharker/G-Shark#280]
At the moment we need to cast to nurbs, probably not ideal

**Comment by sonomirco** [comment]
I would keep perpendicolareFrame only for nurbs, there are plenty of method to construct the frame. What is the advantage to have a metodo construction a frame along a line?

**Comment by sonomirco** [comment]
@cesarecaoduro and @d3ssy can we close this issue, we have `PerpendicularFrameAt` implemented at the level of `NurbsBase` should be enough. Or do we want a specialized version for `Arc/Circle`?

**Comment by sonomirco** [comment]
@d3ssy, can we close this one?
