### ISSUE TITLE
Implement PolyCurve.IsValid

### ISSUE THREAD

**Issue by cesarecaoduro** [GSharker/G-Shark#282]
I will add this as a issue to be further developed

_Originally posted by @cesarecaoduro in https://github.com/GSharker/G-Shark/pull/278#discussion_r694598030_

**Comment by sonomirco** [comment]
@cesarecaoduro Can you specify what defines a valid PolyCurve?

**Comment by cesarecaoduro** [comment]
Should be continuous and not contain isolated segments.

**Comment by sonomirco** [comment]
Should the `ToNurbsForm()` ensure we don't have isolated segments?

**Comment by cesarecaoduro** [comment]
It should, but if we want to run the check before we convert to nurbs, we need this method.

**Comment by sonomirco** [comment]
But the `toNurbsForm()` is called every time you append a curve or create the poly curve, so you already have a nurbs.

**Comment by cesarecaoduro** [comment]
Then I am ok to close this.

**Comment by sonomirco** [comment]
Just so you know, it is no more required, as explained above.
