### ISSUE TITLE
Constructor taking a ``IList<ICurve>`` and the ``Append`` is the method to add single curves.

### ISSUE THREAD

**Issue by cesarecaoduro** [GSharker/G-Shark#283]
Maybe this one could be a constructor taking a ``IList<ICurve>`` and the ``Append`` is the method to add single curves.
Here you can do the checks to validate the ``Polyline``, also because one curve is not a ``Polyline``.

_Originally posted by @sonomirco in https://github.com/GSharker/G-Shark/pull/278#discussion_r694542145_

**Comment by sonomirco** [comment]
@cesarecaoduro is this solve the issue?
https://github.com/GSharker/G-Shark/blob/38fa71781bde9f3a5b60c3310d93540e810e7af8/src/GShark/Geometry/PolyCurve.cs#L95

Or is it something else?

**Comment by cesarecaoduro** [comment]
Yes it does
