### ISSUE TITLE
Extra vector angle function.

### ISSUE THREAD

**Issue by wilham7** [GSharker/G-Shark#407]
Hey there,

I've been using the VectorAngle and VectorAngleOnPlane functions.

I would like the possibility to use the VectorAngleOnPlane function and ALWAYS receive the angle between A and B, regardless of if it is reflex or regular angle. This is how the VectorAngle function works as does the Rhino vector and angle method.

https://developer.rhino3d.com/api/RhinoCommon/html/M_Rhino_Geometry_Vector3d_VectorAngle_1.htm

Thanks!

**Comment by sonomirco** [comment]
Using the current `VectorAngleOnPlane`, the angle returned could be internal or the `reflexAngle`.
It would be nice to have this method passing returning only the angle between the vectors as `Vector3d.VectorAngle` in Rhinocommon does.
https://github.com/mcneel/rhinocommon/issues/178
